### ISSUE TITLE
"Aktuelle" Commits ins Live-System übernehmen

### ISSUE THREAD

**Issue by t-aus-m** [zottelchin/Mensa-Ingo#14]
Mein letzter Commit ist noch nicht online. Pls fix!

**Comment by moqmar** [comment]
Ich bin auf 0f32645, wie es am 2. April um 15:11 auf Docker Hub gebaut wurde. Auch https://mensa.momar.xyz/style.css ist aktuell. Du hast jedoch `backgroud-color` verwendet, was in dieser Schreibweise keine gültige CSS-Eigenschaft ist. Habe das soeben behoben und die neue Version 9c4e6fd auf dem Server installiert. :upside_down_face:

**Comment by t-aus-m** [comment]
Derp. :man_facepalming:
